/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
export interface DatabaseMedia {
  datetime: Date;
  hash: string;
  latitude?: number | null;
  longitude?: number | null;
  make: string;
  model: string;
  path: string;
}
