/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
export interface DatabaseAlbums {
  id?: number;
  parent?: number | null;
  title: string;
}
export interface DatabasePhotos {
  album: number;
  created: Date;
  hash: string;
  height: number;
  width: number;
}
