/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
export interface DatabaseAlbums {
  id?: number;
  parent?: number | null;
  title: string;
}
export interface DatabasePhotos {
  album?: number | null;
  created?: Date | null;
  hash: string;
  height?: number | null;
  width?: number | null;
}
